"""add ai_classification_flags and ai_formulas to cleaned_datasets

Revision ID: d67eafa7ec62
Revises: p7q8r9s0t1u2
Create Date: 2026-03-03 20:24:29.226388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd67eafa7ec62'
down_revision: Union[str, Sequence[str], None] = 'p7q8r9s0t1u2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cleaned_datasets', sa.Column('ai_classification_flags', sa.JSON(), nullable=True))
    op.add_column('cleaned_datasets', sa.Column('ai_formulas', sa.JSON(), nullable=True))
    op.alter_column('cleaned_datasets', 'boolean_category_flags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Flags from Boolean, Category, Status, Survey & Multi-Value cleaning (Session 8)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cleaned_datasets', 'boolean_category_flags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Flags from Boolean, Category, Status, Survey & Multi-Value cleaning (Session 8)',
               existing_nullable=True)
    op.drop_column('cleaned_datasets', 'ai_formulas')
    op.drop_column('cleaned_datasets', 'ai_classification_flags')
    # ### end Alembic commands ###
